// -------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// -------------------------------------------------------------------------------------------------

namespace Microsoft.Health.Fhir.Ingest.Telemetry
{
    /// <summary>
    /// Defines known metrics for use in Application Insights
    /// </summary>
    public static class Metrics
    {
        /// <summary>
        /// The latency between event ingestion and output to FHIR processor.
        /// </summary>
        public static string MeasurementIngestionLatency => nameof(Metrics.MeasurementIngestionLatency);

        /// <summary>
        /// The number of measurement groups generated by the FHIR processor based on provided input.
        /// </summary>
        public static string MeasurementGroup => nameof(Metrics.MeasurementGroup);

        /// <summary>
        /// The number of measurement readings to import to FHIR.
        /// </summary>
        public static string Measurement => nameof(Metrics.Measurement);

        /// <summary>
        /// The number of input events received.
        /// </summary>
        public static string DeviceEvent => nameof(Metrics.DeviceEvent);

        /// <summary>
        /// The number of normalized events generated for further processing.
        /// </summary>
        public static string NormalizedEvent => nameof(Metrics.NormalizedEvent);

        /// <summary>
        /// The latency between the event ingestion time and normalization processing. An increase here indicates a backlog of messages to process.
        /// </summary>
        public static string DeviceEventProcessingLatency => nameof(Metrics.DeviceEventProcessingLatency);
    }
}
