// -------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// -------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using EnsureThat;
using Microsoft.Health.Fhir.Ingest.Telemetry.Metrics;

namespace Microsoft.Health.Fhir.Ingest.Telemetry
{
    /// <summary>
    /// Defines known metrics and metric dimensions for use in Application Insights
    /// </summary>
    public static class IomtMetrics
    {
        private static string _nameDimension = DimensionNames.Name;
        private static string _categoryDimension = DimensionNames.Category;
        private static string _typeDimension = DimensionNames.ErrorType;
        private static string _stageDimension = DimensionNames.Stage;

        private static Metric _measurementIngestionLatency = new Metric(
            "MeasurementIngestionLatency",
            new Dictionary<string, object>
            {
                { _nameDimension, "MeasurementIngestionLatency" },
                { _categoryDimension, Category.Latency },
                { _stageDimension, ConnectorStage.FHIRConversion },
            });

        private static Metric _measurementGroup = new Metric(
            "MeasurementGroup",
            new Dictionary<string, object>
            {
                { _nameDimension, "MeasurementGroup" },
                { _categoryDimension, Category.Traffic },
                { _stageDimension, ConnectorStage.FHIRConversion },
            });

        private static Metric _measurement = new Metric(
            "Measurement",
            new Dictionary<string, object>
            {
                { _nameDimension, "Measurement" },
                { _categoryDimension, Category.Traffic },
                { _stageDimension, ConnectorStage.FHIRConversion },
            });

        private static Metric _deviceEvent = new Metric(
            "DeviceEvent",
            new Dictionary<string, object>
            {
                { _nameDimension, "DeviceEvent" },
                { _categoryDimension, Category.Traffic },
                { _stageDimension, ConnectorStage.Normalization },
            });

        private static Metric _normalizedEvent = new Metric(
            "NormalizedEvent",
            new Dictionary<string, object>
            {
                { _nameDimension, "NormalizedEvent" },
                { _categoryDimension, Category.Traffic },
                { _stageDimension, ConnectorStage.Normalization },
            });

        private static Metric _deviceEventProcessingLatency = new Metric(
            "DeviceEventProcessingLatency",
            new Dictionary<string, object>
            {
                { _nameDimension, "DeviceEventProcessingLatency" },
                { _categoryDimension, Category.Latency },
                { _stageDimension, ConnectorStage.Normalization },
            });

        /// <summary>
        /// The latency between event ingestion and output to FHIR processor.
        /// </summary>
        public static Metric MeasurementIngestionLatency()
        {
            return _measurementIngestionLatency;
        }

        /// <summary>
        /// The number of measurement groups generated by the FHIR processor based on provided input.
        /// </summary>
        public static Metric MeasurementGroup()
        {
            return _measurementGroup;
        }

        /// <summary>
        /// The number of measurement readings to import to FHIR.
        /// </summary>
        public static Metric Measurement()
        {
            return _measurement;
        }

        /// <summary>
        /// The number of input events received.
        /// </summary>
        public static Metric DeviceEvent()
        {
            return _deviceEvent;
        }

        /// <summary>
        /// The number of normalized events generated for further processing.
        /// </summary>
        public static Metric NormalizedEvent()
        {
            return _normalizedEvent;
        }

        /// <summary>
        /// The latency between the event ingestion time and normalization processing. An increase here indicates a backlog of messages to process.
        /// </summary>
        public static Metric DeviceEventProcessingLatency()
        {
            return _deviceEventProcessingLatency;
        }

        public static Metric UnhandledException(string exceptionName, string connectorStage)
        {
            EnsureArg.IsNotNull(exceptionName);
            return new Metric(
                exceptionName,
                new Dictionary<string, object>
                {
                    { _nameDimension, exceptionName },
                    { _categoryDimension, Category.Errors },
                    { _typeDimension, ErrorType.GeneralError },
                    { _stageDimension, connectorStage },
                });
        }

        public static Metric HandledException(string exceptionName, string connectorStage)
        {
            return new Metric(
                exceptionName,
                new Dictionary<string, object>
                {
                    { _nameDimension, exceptionName },
                    { _categoryDimension, Category.Errors },
                    { _typeDimension, ErrorType.GeneralError },
                    { _stageDimension, connectorStage },
                });
        }
    }
}
