//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Health.Extensions.Fhir.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FhirResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FhirResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Health.Extensions.Fhir.Resources.FhirResources", typeof(FhirResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify that the provided FHIR service&apos;s &apos;FHIR Data Writer&apos; role has been assigned to the applicable Azure Active Directory security principal or managed identity..
        /// </summary>
        public static string FhirServiceAccessForbidden {
            get {
                return ResourceManager.GetString("FhirServiceAccessForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify that the FHIR service URL is provided and is an absolute URL..
        /// </summary>
        public static string FhirServiceEndpointInvalid {
            get {
                return ResourceManager.GetString("FhirServiceEndpointInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify that the provided FHIR service exists..
        /// </summary>
        public static string FhirServiceHttpRequestError {
            get {
                return ResourceManager.GetString("FhirServiceHttpRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify that the provided FHIR service URL is a base URL and exists in the applicable Azure Active Directory tenant..
        /// </summary>
        public static string FhirServiceMsalServiceError {
            get {
                return ResourceManager.GetString("FhirServiceMsalServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify that the provided URL is for a FHIR service..
        /// </summary>
        public static string FhirServiceNotFound {
            get {
                return ResourceManager.GetString("FhirServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify that the provided FHIR service URL is an absolute URL..
        /// </summary>
        public static string FhirServiceUriFormatInvalid {
            get {
                return ResourceManager.GetString("FhirServiceUriFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name or service not known.
        /// </summary>
        public static string HttpRequestErrorNotKnown {
            get {
                return ResourceManager.GetString("HttpRequestErrorNotKnown", resourceCulture);
            }
        }
    }
}
